### ISSUE TITLE
Empty result in eval mode of DACSE2018 Task1a baseline

### ISSUE THREAD

**Issue by dby124** [DCASE-REPO/dcase2018_baseline#29]
When I  run the dcase 2018 task1a baseline in eval mode, I found the evaluation datasets named db_eval.test('all_data') in do_testing function is empty.

The problem lead to the empty 'eval_recognizer/res_fold_1.txt'.

**Comment by toni-heittola** [comment]
This error is due to bug in `dcase_util`package, dataset without reference meta data resulted empty cross-validation data in the dataset class. It has been fixed in commit https://github.com/DCASE-REPO/dcase_util/commit/a361d6f78d35405faf1140cbccd4c9eebc9c210d

Upgrade `dcase_util` to version 0.2.10 to correct this issue.
